version: '3.8'

services:
  sccosmetics:
    build: .
    container_name: sccosmetics
    volumes:
      - ./public/available-dates.json:/app/public/available-dates.json:ro
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - platform_proxy-net

networks:
  platform_proxy-net:
    external: true
