version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./public/available-dates.json:/app/public/available-dates.json:ro
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy-net
